### ISSUE TITLE
Order email not sending

### ISSUE THREAD

**Issue by supportA3WEB** [E-Transactions-CA/etransactions23#4]
Bonjour,
Nous venons de mettre à jour votre module en 2.0.3 sur un magento 2.3.6-p1 et sommes en environnement de test. Lorsque nous passons une commande avec le paiement par carte bancaire sur le site, tout se passe bien dans le tunnel de commande jusqu’à la confirmation de commande. Cependant, ni le client ni l'administrateur ne reçoit de mail de confirmation de commande.
Quand j'essaie de passer par les modes de paiements natifs tel que le paiement par chèque, cela fonctionne bien. Idem si on génère une facture via l'administration, on va bien recevoir le mail. 
Pouvez-vous voir si vous renouvelez ? Si oui, comment fonctionne l'envoi de mail via votre module ?

**Comment by jcpaybox** [comment]
Bonjour,

merci pour votre message.

ce problème vient d'être adressé avec la version 2.0.3.1 mise en ligne à l'instant.

**Comment by GhostvOne** [comment]
Problème non résolu à ce que je vois et ticket fermé. 
Pour clarifier le problème : vous vous servez de votre propre fonction pour envoyer l'email de confirmation et allant chercher le template de facturation. 
Vous devriez utiliser la dépendance native de Magento pour envoyer l'email de confirmation ce qui aura pour effet : 

1. De mettre à jour le flag "email_sent" dans l'order
2. D'envoyer les copies d'emails au personnes qui sont paramétrées en back-office si certaines personnes veulent suivre les commandes
3. etc.

Je peux éventuellement vous envoyer un fix mais je suis étonné de voir que le ticket ait été fermé sans résolution

@jcpaybox
