### ISSUE TITLE
Class CreditAgricole\Etransactions\Model\Creditagricole does not exist

### ISSUE THREAD

**Issue by thedotwriter** [E-Transactions-CA/etransactions23#5]
Bonjour,

La version 2.0.3 ne fonctionne pas (en tout cas en mode Developer).

Depuis le checkout, au moment de la redirection vers la banque, une erreur 500 est lancée : 
`[2021-07-01 13:33:32] report.CRITICAL: Class CreditAgricole\Etransactions\Model\Creditagricole does not exist`

L'erreur viens d'un mauvais nommage. Le fichier `vendor/creditagricole/etransactions/Model/creditagricole.php` devrait commencer par une majuscule : `vendor/creditagricole/etransactions/Model/Creditagricole.php`. Sans ça, Magento ne trouve pas le fichier.

**Comment by jcpaybox** [comment]
Bonjour,

Merci pour votre contribution, nous venons de corriger dans la version 2.0.3.1.

Cordialement,

jerome

**Comment by thedotwriter** [comment]
Merci pour la correction rapide.

Néanmoins la nouvelle release n'est pas disponible sur packagist (https://packagist.org/packages/creditagricole/etransactions).

La syntaxe de votre numéro de version n'est peut être pas compatible. Pouvez-vous rester sur la syntaxe initiale ? (x.x.x, soit MAJEUR.MINEUR.PATCH : https://semver.org/spec/v2.0.0.html)

**Comment by thedotwriter** [comment]
C'est tout bon.

Merci
